apiVersion: v1
kind: ServiceAccount
metadata:
  name: corigine-nic-monitor
  namespace: monitoring
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: corigine-nic-monitor
  name: corigine-nic-monitor
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: corigine-nic-monitor
roleRef:
  name: corigine-nic-monitor
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: corigine-nic-monitor
    namespace: monitoring
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: corigine-nic-monitor
  namespace: monitoring
  annotations:
    kubernetes.io/description: |
      This daemon set launches the corigine nic monitor daemon.
spec:
  selector:
    matchLabels:
      app: corigine-nic-monitor
  template:
    metadata:
      labels:
        app: corigine-nic-monitor
    spec:
      containers:
      - args:
        - nic-monitor
        - --listen-port=10770
        image: registry.cn-hangzhou.aliyuncs.com/corigine/nic-monitor:v1.0.0
        name: corigine-nic-monitor
        securityContext:
          runAsUser: 0
          privileged: true
        env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
        volumeMounts:
            - mountPath: /var/log/corigine-nic-monitor
              name: log-path
            - mountPath: /var/run
              name: cri-runtime-path
            - mountPath: /sys/kernel/debug
              name: debug-path
        resources:
          limits:
            cpu: 250m
            memory: 1024Mi
          requests:
            cpu: 102m
            memory: 512Mi
      serviceAccountName: corigine-nic-monitor
      hostNetwork: true
      hostPID: true
      nodeSelector:
        kubernetes.io/os: linux
      volumes:
        - name: log-path
          hostPath:
            path: /var/log/corigine-nic-monitor
        - name: cri-runtime-path
          hostPath:
            path: /var/run
        - name: debug-path
          hostPath:
            path: /sys/kernel/debug
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 10%
    type: RollingUpdate

